# Generated by Django 4.2.5 on 2023-09-11 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('date_naissance', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LangueParlee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MembreEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MotCle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mot_cle', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaysProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Realisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('revenu', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('popularite', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('duree', models.PositiveIntegerField(blank=True, null=True)),
                ('note_moyenne', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('nombre_votes', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_sortie', models.DateField(blank=True, null=True)),
                ('acteurs', models.ManyToManyField(blank=True, related_name='films', to='films.acteur')),
                ('equipe', models.ManyToManyField(blank=True, related_name='films', to='films.membreequipe')),
                ('genres', models.ManyToManyField(blank=True, related_name='films', to='films.genre')),
                ('langues_parlees', models.ManyToManyField(blank=True, related_name='films', to='films.langueparlee')),
                ('mots_cles', models.ManyToManyField(blank=True, related_name='films', to='films.motcle')),
                ('pays_production', models.ManyToManyField(blank=True, related_name='films', to='films.paysproduction')),
                ('realisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='films.realisateur')),
            ],
        ),
    ]
