# Generated by Django 4.2.5 on 2023-09-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_film_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='image',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
