# Generated by Django 4.2.5 on 2023-09-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_alter_film_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='date_sortie',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
