# Generated by Django 4.2.5 on 2023-09-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_userprofile_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='homepage',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
